# Generated by Django 2.2.6 on 2019-11-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=50)),
                ('imagem', models.ImageField(default='rest_promonorte/media/None/no-img.jpg', upload_to='rest_promonorte/media')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=40)),
                ('valor', models.FloatField(max_length=10)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_back.Categoria')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Promocoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=300)),
                ('desconto', models.IntegerField(max_length=3)),
                ('desc_pagamento', models.IntegerField(max_length=1)),
                ('relevancia', models.IntegerField(max_length=1)),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_back.Empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_back.Produto')),
            ],
            options={
                'db_table': 'promocoes',
            },
        ),
    ]
