# Generated by Django 2.2.6 on 2019-11-30 19:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocoes',
            name='dataFinal',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocoes',
            name='dataInicial',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Promocat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_back.Categoria')),
                ('cod_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_back.Produto')),
            ],
            options={
                'db_table': 'promocat',
            },
        ),
    ]
